### ISSUE TITLE
Adicionar função ao código do jogo

### ISSUE THREAD

**Issue by Fabiano23** [nicolycosta/Jogo-Adivinhe-qual-o-filme#1]
Olá, Nicoly, como vai? Antes demais nada quero dizer que achei muito bacana o jogo que criou, parabéns! 

Gostaria de dar duas dicas que me veio à cabeça ao ler o código: 

Dica 1: transformar a parte que é perguntado ao usuário "Qual o filme?" em uma função. Nesse sentido, essa parte não se repetiria no seu código e ele ficaria mais enxuto. 

Dica 2: Tendo em vista a necessidade de escolhas dos filmes para que o jogo ocorra, talvez fosse bacana transformar cada filme em uma variável e todos elas fossem inseridas em uma lista. A partir da chamada de um elemento dessa lista por vez na função que pergunta "Qual o nome do filme?", ocorreria a verificação se o usuário digitou o filme corretamente ou não.

Acredito que haveria menos código repetido desta forma.

Mais uma vez, parabéns pelo jogo, muito bacana.
Abraço!

**Comment by nicolycosta** [comment]
Muito obrigada pela dica, tenho que melhorar mesmo, farei isso.
